from algorithms.nearsighted_player import NearSighted
from algorithms.heuristic_player import HeuristicPlayer
from algorithms.random_player import RandomPlayer

from algorithms.negamax import Negamax
from algorithms.negamax_alpha_beta import NegamaxAlphaBeta
from algorithms.negamax_alpha_beta_depth import NegamaxAlphaBetaDepth
from algorithms.negamax_alpha_beta_ids import NegamaxAlphaBetaIDS


